# Generated by Django 5.2.10 on 2026-01-22 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('konami_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='imports/')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='imports/')),
                ('mode', models.CharField(choices=[('merge', 'Merge'), ('replace', 'Replace')], default='merge', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(blank=True, default='Unlimited', max_length=50)),
                ('condition', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('misprint', models.TextField(blank=True, null=True)),
                ('psa', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('value_low', models.FloatField(blank=True, null=True)),
                ('value_mid', models.FloatField(blank=True, null=True)),
                ('value_high', models.FloatField(blank=True, null=True)),
                ('effective_mid', models.FloatField(blank=True, null=True)),
                ('pricing_source', models.CharField(blank=True, max_length=64, null=True)),
                ('exported_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_entries', to='collection.card')),
                ('card_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_entries', to='collection.cardset')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='collection.importbatch')),
            ],
            options={
                'unique_together': {('card', 'card_set', 'edition', 'psa')},
            },
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='collection_images/')),
                ('collection_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.collectioncard')),
            ],
        ),
    ]
