# Generated by Django 5.2.10 on 2026-01-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectioncard',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='collectioncard',
            constraint=models.UniqueConstraint(fields=('exported_id', 'import_batch'), name='uq_exported_card_per_batch'),
        ),
    ]
