# Generated by Django 5.2.10 on 2026-01-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collectioncard_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncard',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
    ]
