# Generated by Django 5.2.10 on 2026-01-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collectioncard_reserved'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collectioncard',
            name='uq_exported_card_per_batch',
        ),
    ]
