# Generated by Django 5.2.10 on 2026-01-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_remove_collectioncard_uq_exported_card_per_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_order_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='paid', max_length=50)),
                ('shipping_name', models.CharField(blank=True, max_length=255)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('items', models.JSONField()),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
